# Generated by Django 5.1.5 on 2025-01-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_actor_actor_name_en_actor_actor_name_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(blank=True, null=True, upload_to='actor_images'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.actor'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.director'),
        ),
    ]
