# Generated by Django 5.1.5 on 2025-01-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_actor_actor_image_alter_genre_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='director_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.country'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_genre', to='media.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_movie', to='media.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_movie', to='media.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_movie', to='media.genre'),
        ),
    ]
