# Generated by Django 5.1.5 on 2025-01-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_director_director_country_alter_genre_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_movie', to='media.actor'),
        ),
    ]
