# Generated by Django 5.1.5 on 2025-01-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_remove_genre_actor_remove_genre_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='genre_actor',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='genre_director',
            new_name='genre',
        ),
    ]
