# Generated by Django 5.1.5 on 2025-01-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_rename_genre_actor_actor_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_genre', to='media.genre'),
        ),
        migrations.AlterField(
            model_name='director',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_genre', to='media.genre'),
        ),
    ]
