# Generated by Django 5.1.5 on 2025-01-25 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_actor_genre_alter_director_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='director',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.actor'),
        ),
        migrations.AddField(
            model_name='genre',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.director'),
        ),
    ]
