# Generated by Django 5.1.5 on 2025-01-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_remove_genre_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='director',
        ),
        migrations.CreateModel(
            name='GenreSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.director')),
                ('genre_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.genre')),
            ],
        ),
    ]
