# Generated by Django 5.1.5 on 2025-01-25 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_remove_genresimple_director_genre_genre_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='director',
        ),
        migrations.AlterField(
            model_name='genresimple',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_genre', to='media.director'),
        ),
    ]
