# Generated by Django 5.1.5 on 2025-01-25 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_remove_genre_director_alter_genresimple_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='genresimple',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='media.movie'),
        ),
    ]
