# Generated by Django 5.1.5 on 2025-01-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_remove_movie_genre_genre_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='types',
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveSmallIntegerField(choices=[(144, 144), (360, 360), (480, 480), (720, 720), (1080, 1080)], default=720)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_types', to='media.movie')),
            ],
        ),
    ]
